### ISSUE TITLE
Reset Device for Calibration

### ISSUE THREAD

**Issue by hardikrshah007** [xsens/xsens_mti_ros_node#10]
Hi Everyone 

I am using the IMU Mti-3 (development kit) version in ROS. I am using the filter VRU which provides me with unreferenced Yaw. I am using the IMU data in AMCL planner for mobile robots. 

At the beginning when the robot is turned on, I would like to do the following things

1. Reset the Gyroscope and Accelerometer to zero in order to calibrate as I know that my robot is stationary
2. Reset the Heading for the Yaw reading to zero ( i don't know what that value would be in Quaternion form)

**Comment by arunvydhya** [comment]
@hardikrshah007 The reset command when sent while using in the 'vru_general' filter profile reinitializes the filter which will initialize the yaw reading to zero.

**Comment by arunvydhya** [comment]
@hardikrshah007 you can already use the predefined 'reset' message by using the -r options that should do the trick. However this would however put the device to factory defaults. For in-run use, the node can be easily tweaked to send in a 'ResetOrientation' message with the code for heading reset. This can be done in-run (measurement mode). This should work for your application needs.

**Comment by cherishyuan** [comment]
> Hi Everyone
> 
> I am using the IMU Mti-3 (development kit) version in ROS. I am using the filter VRU which provides me with unreferenced Yaw. I am using the IMU data in AMCL planner for mobile robots.
> 
> At the beginning when the robot is turned on, I would like to do the following things
> 
> 1. Reset the Gyroscope and Accelerometer to zero in order to calibrate as I know that my robot is stationary
> 2. Reset the Heading for the Yaw reading to zero ( i don't know what that value would be in Quaternion form)

May I ask how you solved this problem?

**Comment by Steven-GH** [comment]
> > Hi Everyone
> > I am using the IMU Mti-3 (development kit) version in ROS. I am using the filter VRU which provides me with unreferenced Yaw. I am using the IMU data in AMCL planner for mobile robots.
> > At the beginning when the robot is turned on, I would like to do the following things
> > 
> > 1. Reset the Gyroscope and Accelerometer to zero in order to calibrate as I know that my robot is stationary
> > 2. Reset the Heading for the Yaw reading to zero ( i don't know what that value would be in Quaternion form)
> 
> May I ask how you solved this problem?

Hi @cherishyuan,

This ROS node has been discontinued. I recommend using the following ROS1/ROS2 driver instead, which provides more configuration options as well:
https://github.com/jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client

For further support, it is best to contact Xsens at https://www.movella.com/support/request-support
