### ISSUE TITLE
ttyUSB0 does not exist 

### ISSUE THREAD

**Issue by rigersrukaj** [xsens/xsens_mti_ros_node#12]
I am trying to connect a FMT1030 device on a development/evaluation board to my Jetson TK1 embedded system. However, once I enter the following line:
rosrun xsens_driver mtdevice.py -m 1 -f 100
I get the following error:
'MT error: unable to open /dev/ttyUSB0'

The folder does not seem to exist on the system. lsusb shows the device is connected however

Unfortunately have not been able to find a 32bit software suite for the FMT1030 but I have downloaded the prerequisites from this repository. Not sure if this would be the issue

**Comment by arunvydhya** [comment]
@rigersrukaj have you tried following the steps listed in the troubleshooting section?
