### ISSUE TITLE
True heading

### ISSUE THREAD

**Issue by muggeru** [xsens/xsens_mti_ros_node#15]
Hi,

I currently have the xsens MTi-G-710 which should offer True Heading. However i can't find out where to get this data. Does your node publish this data and if so, in what topic?
If not, any idea where i can start to get this data?

The /mti/filter/orientation data offer a Yaw angle, but it drifts quite alot. I've also tried to calculate true north from the /mti/sensor/magnet topic but since i have a lot of rolling and pitching motion this is quite unaccurate i believe.

(Adding in that i'm fairly new to ROS)
Any help appreciated!

Thanks

**Comment by arunvydhya** [comment]
@muggeru The data you are looking for is the yaw part of /mti/filter/orientation data message. The drift is on expected lines. Please refer to Section 4.3 of the MTi User Manual that is part of our SDK installation. You can find more details on the unit's behavior and observability issues.
