### ISSUE TITLE
TF does not work

### ISSUE THREAD

**Issue by athtest800** [xsens/xsens_mti_ros_node#16]
Hello!
I make a tf  world>base_link with /mti/sensor/imu.
then a static tf transform base_link>laser
The second tf does not work I get
From frame laser: No transform to fixed frame world.
If i use other imu brand works fine.

**Comment by athtest800** [comment]
Interference with other imu at the same time

**Comment by jediofgever** [comment]
@athtest800  How did you solved this issue ? I am having the same problem
