### ISSUE TITLE
mtnode.py throws a bunch of errors 

### ISSUE THREAD

**Issue by spacemanspiff0211** [xsens/xsens_mti_ros_node#21]
Hey,
I am trying to use this ROS node with my MTi-10, but the ROS node throws a bunch of errors.
the output of `rosrun xsens_driver mtnode.py _device:=/dev/xsens _baudrate:=115200` is 
```

[INFO] [1498865061.446497]: Found parameter: ~device, value: /dev/xsens
[INFO] [1498865061.447545]: Found parameter: ~baudrate, value: 115200
[INFO] [1498865061.447719]: MT node interface: /dev/xsens at 115200 bd.
Traceback (most recent call last):
  File "/home/spacemanspiff/catkin_ws/src/xsens_mti_ros_node/src/xsens_driver/src/mtnode.py", line 373, in <module>
    main()
  File "/home/spacemanspiff/catkin_ws/src/xsens_mti_ros_node/src/xsens_driver/src/mtnode.py", line 368, in main
    driver = XSensDriver()
  File "/home/spacemanspiff/catkin_ws/src/xsens_mti_ros_node/src/xsens_driver/src/mtnode.py", line 61, in __init__
    self.mt = mtdevice.MTDevice(device, baudrate)
  File "/home/spacemanspiff/catkin_ws/src/xsens_mti_ros_node/src/xsens_driver/src/mtdevice.py", line 23, in __init__
    writeTimeout=timeout)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 180, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 311, in open
    self._update_dtr_state()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 605, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
IOError: [Errno 22] Invalid argument

```
I did check the file permissions , everything seems to be alright. The output of `ls -l /dev/xsens`
is `lrwxrwxrwx 1 root root 7 Jun 30 15:57 /dev/xsens -> ttyUSB0`

Thanks

**Comment by arunvydhya** [comment]
can you try running the xsens_driver without any arguments? Is the user part of the 'dialout' group? you can find the steps needed in the TroubleShooting section.

**Comment by raymond30031** [comment]
Hello,

Same issue for me and I am using a MTi-G-710.
I have double checked the permission (chmod 666 /dev/ttyUSB0) and tried it without arguments and the issue still persists.

**Comment by arunvydhya** [comment]
We have not been able to reproduce this on our side on an Indigo , which version of ROS are you using?

**Comment by spacemanspiff0211** [comment]
Hey @arunvydhya 
I am using ROS Kinetic on Ubuntu 16.04.

**Comment by raymond30031** [comment]
same for me

**Comment by arunvydhya** [comment]
We are having some issues with the node in Kinetic. We are looking into this.

**Comment by arunvydhya** [comment]
Can you replace line 22/23 in mtdevice.py with the following and try it? We will commit the changes asap.

self.device = serial.Serial(port, baudrate, timeout=timeout,
writeTimeout=timeout, rtscts=True, dsrdtr=True)

**Comment by arunvydhya** [comment]
@spacemanspiff0211  and @raymond30031  did it work?

**Comment by spacemanspiff0211** [comment]
@arunvydhya : Yep .. That fixes the issue for me..

**Comment by sgarciav** [comment]
Hello,
Seems like this issue was closed but the fix was never committed. Took em a while to find this forum and solve the issue.

**Comment by arunvydhya** [comment]
the commit has been made. Thanks!
