### ISSUE TITLE
[Enhancement] Add ability to change synchronization settings

### ISSUE THREAD

**Issue by raymond30031** [xsens/xsens_mti_ros_node#22]
Hello,

It would be nice to support from the official driver to support configuring the MTi devices synchronizations settings and UTC time

**Comment by arunvydhya** [comment]
Hi @raymond30031, thanks for your request. In general, we tend to avoid adding specific functionalities to the ROS node as it is meant to be as a starting point for system integrators. We leave it up to the users to modify the node based on their application requirements.
