### ISSUE TITLE
the differences with MVN Studio

### ISSUE THREAD

**Issue by chenlx92** [xsens/xsens_mti_ros_node#24]
Hi, thanks for the nice driver. I plan to buy MVN Link or MVN Awinda. I want to confirm some questions listed as below. 
1. Is this ROS driver for both two hardware versions (MVN Link and MVN Awinda)?  We can use it **without any licenses**, and we just need the MVN Link or MVN Awinda hardware, right?
2. You know the main hardware is the inertial sensor. Are there any differences (for example IMU drift) between sensor data from **xsens_mti_ros_node** and **MVN Studio**? The xsens_mti_ros_node give us the **raw data** or **filtered data**?

**Comment by arunvydhya** [comment]
Hello,

1. This MTi ROS driver does not support MVN Link and MVN Awinda.
2. The basis measurement quantities are identical but sample rates differ. The node gives both raw data as well as filtered outputs for the MTi devices (no support for MVN Studio).
