### ISSUE TITLE
Free Acceleration with MTi-3

### ISSUE THREAD

**Issue by OnesoulKang** [xsens/xsens_mti_ros_node#26]
Hi, I'm using MTi-3 DK.

How can I get Free Acceleration data?

and How can I delete bias and drift?

**Comment by arunvydhya** [comment]
@OnesoulKang, you have to modify the mtdevice.py to configure the MTi device to output the free acceleration data. Please use our low-level documentation on the website to get details on the output configuration ID's.  You can also access our support site base.xsens.com to get more information on bias and drift behavior.
