### ISSUE TITLE
Support for RAW Data

### ISSUE THREAD

**Issue by collinsc** [xsens/xsens_mti_ros_node#27]
Hey, I'm with the University of Washington robotics club. We're using one of your MTI-1 or MTI-3 development kit for a NASA contest in the spring, and one of the rules for that contest is that we can't use magnetic data for any of our odometry (because Mars doesn't have a strong magnetic field).  I spoke to an engineer on the phone last Fall, Scott I think his name was, who told me this was possible but not part of the default behavior of this ROS node. My understanding is that the IMU does some sensor fusion before publishing the data.

We received what I thought was the MTI-3 Developent Kit from Xsens as part of a sponsorship for our competition, but the physical chip is labeled MTI-1 Dev Kit.  Our invoice says it's an MTI-3.  I believe either of these works for what we need, but I'm not sure if it changes how the driver is used.

**Comment by arunvydhya** [comment]
“MTi-1s-DEV” on the silk screen simply represents the MTi 1-series. There is only a MTi-3 Development Kit, no MTi-1 development kit. You can configure the sensor as “vru_general” and turn on AHS in MT Manager, then use the ROS node commands to setup the output data as needed (inertial data or orientations).
