### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by cb2411** [xsens/xsens_mti_ros_node#31]
Hi, I am trying to run your ros node but getting the following error messages:
If I run xsens_driver alone using:
```
rosrun xsens_driver mtdevice.py -m 2 -f 10
```
I get the error:
```
TypeError: ord() expected a character, but string of length 0 found
```
If I first run the awindamonitor from your mtsdk examples, 'enable' and undock a sensor (so it shows on the connected MTw list) I get the error
```
MT error: could not find message.
```
(also once I run the xsens_driver, the awindamonitor stops responding)

The dock is plugged into my computer and have tried running xsens_driver both with sensors docked and undocked, the error is the same.

Any help appreciated! Thanks :)

**Comment by arunvydhya** [comment]
The MTi ROS node is meant for MTi devices only. It does not support MTw.
