### ISSUE TITLE
mti-7dk

### ISSUE THREAD

**Issue by G-DWarrior** [xsens/xsens_mti_ros_node#40]
hallo，sir. i use the xsens mti-7-dk. and i git clone your code.
when i finish the step"roslaunch" the terminal tell me cannot find the value for parameter -linear_acceleration and orientation comvariance_diagonal

**Comment by arunvydhya** [comment]
@G-DWarrior not all native ROS messages are supported. 
you can use the command 'rostopic list' to display the list of current topics being published.
