### ISSUE TITLE
xsens MTi-300 can’t driver

### ISSUE THREAD

**Issue by acer317** [xsens/xsens_mti_ros_node#44]
Hi，
I am using Xsens MTI-300 to get imu data for a sensor fusion application. But I can't install the MTi-300 driver now.I follow the tutorial you gave on this site. My system is ubuntu 16.04 and ros Kinetic Kame.I had the following problem .
![questin](https://user-images.githubusercontent.com/39732178/49488123-5a57b580-f880-11e8-8224-5b036255e190.PNG)
How can I solve this problem? Thank you!

**Comment by guangjingli** [comment]
Hi, I meet the same problem. How do you solve it? Thank you!

**Comment by StevenXsens** [comment]
Hello guangjingli,
Are you facing any errors? Have you checked the Troubleshooting section at the end of README.md?
