### ISSUE TITLE
MT error: Unknown device with MTi 1-series

### ISSUE THREAD

**Issue by bradleypowers** [xsens/xsens_mti_ros_node#5]
Trying to run this driver with an MTi-1 eval kit, I've run into an Unknown device error.  In line 443 of mtdevice.py (https://github.com/xsens/xsens_mti_ros_node/blob/master/src/xsens_driver/nodes/mtdevice.py#L443), you have a case statement that checks for the various device IDs, but does not include a case for the MTi-1, which has an ID of 0x38.  You raise an error at this point, and the device doesn't get configured.

**Comment by arunvydhya** [comment]
We will work on this in the coming few weeks, if you have patched the source already you can do a pull request.

**Comment by arunvydhya** [comment]
Support has been added with the new release (v3.0.0)
