### ISSUE TITLE
Motion Tracker Dev. Board(Mti-670):    ord() expected a character, but string of length 0 found

### ISSUE THREAD

**Issue by diennv** [xsens/xsens_mti_ros_node#59]
Hi, 
I tried to use new Xsens board on ROS Melodic (Ubuntu 18.04).
I met the error when i start the node. 
Pls help me to solve this issue. I tested on laptop and desktop.
They have same issue.

**Comment by Steven-GH** [comment]
Hello,

This ROS node implementation is deprecated, and it is not designed for the MTi 600-series. Please try our new official ROS node available as part of the Xsens MT Software Suite (version 2019.0 and later). For more information refer to http://wiki.ros.org/xsens_mti_driver

**Comment by diennv** [comment]
Thank you. The problem is solved by using the provided SDK.

Thanks.
