### ISSUE TITLE
MTi-G-710-2A8G4 on ROS

### ISSUE THREAD

**Issue by ManChrys** [xsens/xsens_mti_ros_node#64]
Hello guys,

i just bought MTi-G-710-2A8G4 and i want to use it on ROS environment.

I followed the directions from the [http://wiki.ros.org/xsens_mti_driver](url) to install the package. I copy the mti ros driver inside my workspace and catkin_make it.

It seems that is working fine but i would like to ask why orientation is 0.0

![Screenshot from 2021-08-06 09-43-19](https://user-images.githubusercontent.com/67521662/128467978-77010cc7-0b2e-4041-8e99-b8e9491a1558.png)

**EDIT**
on windows working fine and i have all the measurements from imu and gps too.

**EDIT_2**

when im running display.launch i have the following error. It seems that it cant find the imu ?

![Screenshot from 2021-08-06 10-00-13](https://user-images.githubusercontent.com/67521662/128469836-59c3ff41-1306-4092-9d41-e1a4cf268d72.png)

**Comment by ManChrys** [comment]
ok its fixed.

**Comment by ManChrys** [comment]
ok i just fix it through MT Manager.

**Comment by flingok** [comment]
> ok i just fix it through MT Manager.

hi, I have the same issue, what is cause,could you please share it to me

**Comment by ManChrys** [comment]
@flingok 

$ sudo usermod -G dialout -a $USER

$ newgrp dialout

And then run again the command.
