### ISSUE TITLE
Interface Diagram for Livox And Xsens Gnss/Ins

### ISSUE THREAD

**Issue by ManChrys** [xsens/xsens_mti_ros_node#67]
Hello guys,

im trying to intergrate my MTi-G-710-2A8G4 with my Livox mid 40 laser scanner. On the diagram you can see my first try but it didnt work. The problem is that the xsens module doesnt appear on terminal when i tried `lsusb` but when i connect xsens directly to pc it worked normally.

![DIAGRAM](https://user-images.githubusercontent.com/67521662/130329210-8b429e00-d292-4a8f-a0fd-2dcd640a78ae.png)

If you can make a section on xsens site like these 

1 )https://base.xsens.com/knowledgebase/s/article/Interfacing-with-Ouster-Lidar-for-Xsens?language=en_US
2) https://base.xsens.com/knowledgebase/s/article/Interfacing-an-MTi-GNSS-INS-device-with-a-Velodyne-Lidar?language=en_US

about livox mid 40 it would be great. Although any help or tips or any diagram would be great.

Thanks in advance.

**Comment by Steven-GH** [comment]
Hello @ManChrys,

This does not seem related to the ROS node... Could you contact Xsens Support for this? You can create a support case via [BASE](https://xsenstechnologies.force.com/knowledgebase/s/?language=en_US). Please then also provide more details on the multiplexer and the interface converters that are being used.

**Comment by ManChrys** [comment]
Hello @StevenXsens 

I have already send an email with full details, print screens of my system, diagrams and links for converters.

I have one more question . If I connect mti through Ttl to usb converter on pc imu should be appeared on `lsusb` ? Using multiplexer converter when I run the `lsusb` command Mti device didn't get recogniZed. I think the reason behind this problem is the multiplexer .I don't know In my opinion the custom usb cable is not suitable for projects like mine because it's hard to sync gnss/ins with lidar and at the same time give data to pc.I think the one cable on xsens eshop with molex pins will be more useful and I think on this one all 9 pins are available something that doesn't happens on the custom usb cable has only 4 pins (VCC,GND,D+,D-) available .

**Comment by Steven-GH** [comment]
Hello @ManChrys,

I am sorry, but your e-mail has not reached the support department. Have you tried e-mailing support@xsens.com?  

Yes, a serial cable that provides access to the RS232/RS485/RS422 and Sync pins of the MTi is usually more practical when trying to synchronize with lidars. The standard USB cable is really only meant for pure USB communication.

**Comment by ManChrys** [comment]
Hello @StevenXsens no I send it on info@xsens.com, 

![image](https://user-images.githubusercontent.com/67521662/130486575-7a733e79-c3b1-4c7f-847b-6342993feb66.jpeg)

but I'll send it on the email you said too. Thank you again my friend.

**Comment by ManChrys** [comment]
@StevenXsens And last but not least. Is this cable https://shop.xsens.com/shop/mti-100-series/accessories/mti-100-series-accessories/ca-mp2-mti the best choice for me ?all 9 pins are easy accessible and I can convert them to anything.

**Comment by Steven-GH** [comment]
@ManChrys Yes, that would be the right cable to use.

**Comment by ManChrys** [comment]
@StevenXsens When I'll try to connect the GNSS/INS using molex pins to pc through ttl to usb converter it will normally read it as xsens mti g710 or there is any chance to not detected as I said above when I used multiplexer ?
