### ISSUE TITLE
Unable to get linear velocity and acceleration outputs on  MTi-30-2A8G4

### ISSUE THREAD

**Issue by kushal2507** [xsens/xsens_mti_ros_node#68]
I am using an  MTi-30-2A8G4 on my mobile robot. When launching the node I can see the outputs in the /imu/data topic which is mostly the orienation but nothing on the /imu/dv or /imu/acceleration. 
Is this particular model not compatible to give linear velocity and acceleration? Or am I missing something in the param file?

All params have been set to true in the query.yaml file

Thank you!

**Comment by Steven-GH** [comment]
Hello @kushal2507,

All MTi product support the dv and acceleration outputs. However you do need to configure your device to output these quantities, for instance using our MT Manager software. In MT Manager, open the Device Settings window, check the required outputs and click Apply:
![image](https://user-images.githubusercontent.com/41789163/143473669-f7343b2e-6ef7-46ab-924e-d925f743c4c6.png)

**Comment by kushal2507** [comment]
Thank you @StevenXsens this solves the issue!
