### ISSUE TITLE
xsens MTi-300 device not found

### ISSUE THREAD

**Issue by Amit10311** [xsens/xsens_mti_ros_node#73]
Hello, 

I would like to mention that I can't find the sensor when using ros but when I am using `mtmanager` I found it. 

```
[ INFO] [1655136331.873229227]: Found device ID parameter: 037003F4.
[ INFO] [1655136331.873438885]: Found port name parameter: /dev/ttyUSB0
[ INFO] [1655136331.873450081]: Scanning port /dev/ttyUSB0 ...
```
My system is ubuntu 18.04 and ros Melodic. How can I solve this problem? Thank you!

**Comment by Steven-GH** [comment]
Hi @Amit10311,

Are you using this (deprecated) ROS node on Github or the one that is included in the Xsens MT SDK?  
After plugging in the MTi, can you open a terminal and share the responses to the _dmesg_ and _lsusb_ commands?

**Comment by Amit10311** [comment]
Hello @itsupportxsens,

Please find the information below: 

```
$ dmesg
[  298.307168] usb 3-3: New USB device found, idVendor=2639, idProduct=0013, bcdDevice= 0.00
[  298.307173] usb 3-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  298.307175] usb 3-3: Product: MTi-300 AHRS
[  298.307177] usb 3-3: Manufacturer: Xsens
[  298.307179] usb 3-3: SerialNumber: 037003F4
[  298.322906] xsens_mt 3-3:1.1: xsens_mt converter detected
[  298.322949] usb 3-3: xsens_mt converter now attached to ttyUSB0
```

```
$ lsusb
Bus 003 Device 009: ID 2639:0013 Xsens MTi-300 AHRS
```

```
$ roslaunch xsens_mti_driver xsens_mti_node.launch 

process[xsens_mti_node-2]: started with pid [4418]
[ INFO] [1655198000.497411269]: Creating XsControl object...
[ INFO] [1655198000.506664097]: Found device ID parameter: 037003F4.
[ INFO] [1655198000.506897580]: Found port name parameter: /dev/ttyUSB0
[ INFO] [1655198000.506907812]: Scanning port /dev/ttyUSB0 ...
[ERROR] [1655198000.512377579]: No MTi device found. Verify port and baudrate.
 ```

**Comment by Steven-GH** [comment]
Hi @Amit10311,

I have just tried the same thing on my side (ROS Melodic, Ubuntu 18.04, MTi-300 connected via USB and device ID + port name parameters provided) and it ran just fine for me... Have you closed MT Manager when running the ROS driver? Could you check if you have the rights to access to the device?  See the troubleshooting steps for "The device is recognized, but I cannot ever access the device." on the following page:
http://wiki.ros.org/xsens_mti_driver

**Comment by Amit10311** [comment]
Hello,

Yes, This one helped it. It's working perfectly. 

 **"The device is recognized, but I cannot ever access the device." on the following page:
http://wiki.ros.org/xsens_mti_driver**

```
$ sudo usermod -G dialout -a $USER

$ newgrp dialout
```

Thank you for the quick response and solution.
