### ISSUE TITLE
Xsens MTIG-710 roslaunch error... process dies

### ISSUE THREAD

**Issue by ahar** [xsens/xsens_mti_ros_node#74]
Hi,

Please find the attached image. I followed the troubleshooting method explained in the readme file. But, the error sustains.

Your help is much appreciated.

regards,

![Selection_019](https://user-images.githubusercontent.com/18175277/177175278-7f79ffc9-5a6d-4b30-81ee-b07d1e966b72.png)

**Comment by Steven-GH** [comment]
Hello @ahar,

It looks like the "xkf_scenario" number you provided in the xsens.yaml configuration file is invalid for the MTi-G-710. Its value should be in the range of 1 to 5. 
Anyway, I highly recommend using the latest ROS (actively maintained) ROS driver which is described here: http://wiki.ros.org/xsens_mti_driver

**Comment by ahar** [comment]
Hi @StevenXsens 
Thanks, that issue is resolved. With the latest software from [here](https://www.xsens.com/software-downloads) I am able to use .`mtmanager` to view the data generated by the sensor. But, I did not find any link for the ROS wrapper on the `wiki` page that you referred. Can you please suggest on this?

**Comment by Steven-GH** [comment]
Hi @ahar,

Have you downloaded the MT Software Suite for MTi products (2021.x)? Then, extract the downloaded installation package, execute the mtsdk_linux-x##_####.#.sh and you will find the xsens_ros_mti_driver folder.

**Comment by ahar** [comment]
Hi,

Thanks for your previous response. While compiling the ros package as described in http://wiki.ros.org/xsens_mti_driver, I find the error attached here. I checked that the respective function declaration exists, although it still shows the error. 
![mti_ros_error](https://user-images.githubusercontent.com/18175277/178492902-e8fbb8f9-f1c0-4682-b119-c68c863f38c7.png)

Please suggest.

**Comment by Steven-GH** [comment]
Hi,

I have the feeling that you are not using the latest xspublic folder contents because the latest one includes a file mti7_mti8device.cpp.o instead of mti7device.cpp.o. Could you try simply copying the complete folder _xsens_ros_mti_driver_ from your MT SDK (v2021.4) to the _src_ folder of your ROS workspace? 

If the problem still shows up, please copy the full terminal trace and send it to support@xsens.com together with your system info (ROS version, Ubuntu version, etc.) such that our support team can have a look at it.

**Comment by ahar** [comment]
Very interestingly, I tried everything inside one of my docker containers. It worked. Also, I checked that `mti7_mti8device.cpp` existed inside the `xspublic` directory while I tried from within my ros workspace outside the container. It might have happened due to a permission issue, although I am not sure. Because I manually checked the `rw` permissions to each file.

Anyway, thank you for the support.
