### ISSUE TITLE
using filtered orientation together with accleration

### ISSUE THREAD

**Issue by tigelbri** [xsens/xsens_mti_ros_node#9]
in case I set the filter mode parameter to 3 (filtered output) on my MTI-G 700 device, without any GPS connected, I will just receive a filtered orientation estimation. Is there a possibility to achieve any other filtered values (acceleration, position)?

By the way I didn’t get the difference between filter mode 1 and 2. Can anyone help?

Cheers!

Tristan

**Comment by arunvydhya** [comment]
@tigelbri - the mode 1 and 2 is to be used if the sensor data is required. For MTi-G-700, the mode 3 will output only orientation (if there is no GPS connected).
